config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
     resources :likes, only: [:create]
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Relationship
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_comment_count
    post.update(comments_counter: post.comments.count)
    post.comments.count
  end
end

app/models/like.rb
class Like < ApplicationRecord
  # Relationship
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
    post.likes.count
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Relationship
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy
  after_save :update_post_counter

  private

  def update_post_counter
    user.update(post_counter: user.posts.count)
  end

  public

  def recent_comments
    comments.order(created_at: :asc).limit(5)
  end

  # VALIDATIONS
  validates :title, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Reletionship
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'user_id', dependent: :destroy

  after_initialize :set_default_post_counter

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  # VALIDATIONS
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  private

  def set_default_post_counter
    self.post_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include CanCan::ControllerAdditions
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email bio password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    # @comment = @post.comments.build(comments_params)
    # @comment.user = current_user
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Comment created successfully.'
      redirect_to users_posts_path(@user, @post)
    else
      flash[:error] = 'Error creating comment.'
      redirect_to user_posts_path
    end
  end

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post: @post)

    if @like.save
      flash[:success] = 'You liked this post!'
      redirect_to user_posts_path
    else
      flash[:alert] = 'Error occured'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div>
<%= form_with(model:[@post, @comment], local: true, url: user_post_comments_path) do |form| %>
   <div>
    <%= form.label :text %><br/>
    <%= form.text_area :text, rows:3, placeholder: 'Enter your Comment' %>
  </div>
  <p>
    <%= form.submit 'Comment' %>
  </p>
<% end %>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, message| %>
<div role="alert">
    <div>
      <%= message %>
      <button type="button" aria-label="Close"></button>
    </div>
</div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application.bootstrap', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render '/layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/likes/_new.html.erb
<div>
<%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form|%>
  <%= form.submit "Like" %>
   <%= link_to "Comment", new_user_post_comment_path(post_id: @post.id) %>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [@user, @post], local: true, url: user_posts_path) do |form| %>
  <div>
    <%= form.label :title, for: "exampleFormControlInput1" %><br/>
    <%= form.text_field :title, id: "exampleFormControlInput1" %>
  </div>
  <div>
    <%= form.label :text, for: "exampleFormControlTextarea1" %><br/>
    <%= form.text_area :text, id: "exampleFormControlTextarea1", rows: "3" %>
  </div>
  <p>
    <%= form.submit 'Create Post' %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Here is the list of all posts</h1>
<div> 
  <span><img src="https://picsum.photos/id/64/200" alt="..."></span>
   <span>name: <%= @user.name %></span>
   <span>number of posts: <%= @user.posts.count %></span>
      <% @user.posts.each do |post| %>
        <div>Post # <%= post.id %>
        <%= link_to  post.text, user_post_path(@user, post) %>
        </div>
        <div>
        <span>Comments: <%= post.comments.count %></span>
        <span>Likes: <%= post.likes.count %></span>
        </div>
        <ul>
        <% post.recent_comments.each do |comment| %>
          <li>Username: <%= User.find(comment.user_id).name %> comment: <%= comment.text %></li>
        <% end %>
        </ul>
      <% end %>
    
  <div>
   <%= link_to 'Create new post', new_user_post_path %>
  </div>
  <% if@user.posts.count > 3 %>
  <div class="pagination">
    <button>Pagination</button>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div>
<h1>Create new Post</h1>
<%= render 'form' %>
<%= link_to 'Back to list of posts', user_posts_path %>
</div>

app/views/posts/show.html.erb
<h1>Here are post description of a user<h1>
<div>
    <div>
      <div>Post # <%= @post.id %> by <%= User.find(@post.author_id).name %>
    </div>
      <%= @post.text  %>
    </div>
    <div>
      <span>Comments: <%= @post.comments.count%></span>
      <span>Likes: <%= @post.likes.count %></span>
    </div>
  <ul>
   <% @post.comments.each do |comment| %>
   <li>Username:  <%= User.find(comment.user_id).name %>,  Comment:  <%= comment.text%> </li> 
   <%end%>
  </ul>
 <div>
 <%= render 'likes/new', post: @post, like: @like %>
 <%= link_to 'Go to posts page', user_posts_path %>
 </div>
</div>

app/views/users/index.html.erb
<div>
<h1>Here is the list of all users</h1>
<div>
  <h1>Users</h1>
  <ul>
    <% @users.each do |user| %>
      <li>
        <span><img src="https://picsum.photos/id/64/200" alt="..."></span>
        <li>
       <%= link_to user_path(user) do %>
            <h2><%= user.name %></h2>
          <% end %>
        <span> Number of posts: <%= user.posts.count %> </span>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<h1>This page shows the users posts and comments<h1>
<div>
  <span><img src="https://picsum.photos/id/64/200" alt="..."></span>
  <span>
   name: <%= @user.name %>
  <span> number of posts: <%= @user.posts.count %> </span>
  </span>
    <h5>Bio</h5>
    <p><%= @user.bio  %></p>

  <% @user.posts.each do |post| %>
    <li>
    <div>
     <div> <%="title: #{post.title}"%></div>
      <div><%=link_to  post.text, user_post_path(@user, post) %></div>
    </div>
    <div>
    <span>Comments: <%= post.comments.count%></span>
    <span>Likes:<%= post.likes.count %></span>
    </div>
  </li>
  <%end%>
<div>
 <%= link_to user_posts_path(@user) do %>
  <button>See all posts</button>
 <% end %>
</div>
</div>